# Generated by Django 6.0.4 on 2026-05-28 07:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(max_length=50, unique=True, verbose_name='Идентификатор Wikidata (QID)')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Средний рейтинг')),
                ('review_count', models.IntegerField(default=0, verbose_name='Количество оценок')),
            ],
            options={
                'verbose_name': 'Культурный объект',
                'verbose_name_plural': 'Культурные объекты',
                'indexes': [models.Index(fields=['wikidata_id'], name='map_app_pla_wikidat_6058bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wikidata_id', models.CharField(help_text='Идентификатор объекта (QID)', max_length=50)),
                ('place_label', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'indexes': [models.Index(fields=['user', 'wikidata_id'], name='map_app_fav_user_id_8ca400_idx')],
                'unique_together': {('user', 'wikidata_id')},
            },
        ),
    ]
