# Generated by Django 6.0.4 on 2026-05-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местность/Город'),
        ),
    ]
