# Generated by Django 6.0.4 on 2026-05-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='external_id',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
